/**
 * Theme-native styles, injected as a plugin-owned <style> tag (the web boot
 * loader claims and removes tags carrying data-plugin on unload).
 */

export const STYLES = [
  '.lc-root { padding: 16px 20px 32px; overflow-y: auto; height: 100%; box-sizing: border-box; color: var(--dsw-alias-label-primary); font-size: 13px; }',
  '.lc-card { background: var(--dsw-alias-bg-layer-1); border: 1px solid var(--dsw-alias-border-l1); border-radius: 10px; padding: 14px 16px; margin-bottom: 14px; }',
  '.lc-card-title { font-weight: 600; margin-bottom: 10px; display: flex; align-items: baseline; gap: 8px; }',
  '.lc-stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(92px, 1fr)); gap: 8px; }',
  '.lc-stat { background: var(--dsw-alias-bg-layer-2); border: 1px solid var(--dsw-alias-border-l1); border-radius: 8px; padding: 8px 10px; display: flex; flex-direction: column; gap: 2px; min-width: 0; }',
  '.lc-stat-label { color: var(--dsw-alias-label-secondary); font-size: 11px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }',
  '.lc-stat-value { color: var(--dsw-alias-label-primary); font-size: 14px; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }',
  '.lc-stat-sub { color: var(--dsw-alias-label-secondary); font-size: 11px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }',
  '.lc-card-sub { font-weight: 400; color: var(--dsw-alias-label-secondary); font-size: 12px; }',
  '.lc-gran { margin-left: auto; display: flex; gap: 2px; background: var(--dsw-alias-bg-layer-2); border: 1px solid var(--dsw-alias-border-l1); border-radius: 6px; padding: 1px; }',
  '.lc-gran-btn { border: 0; background: transparent; color: var(--dsw-alias-label-secondary); font-size: 11px; line-height: 1; padding: 3px 8px; border-radius: 5px; cursor: pointer; font-family: inherit; }',
  '.lc-gran-btn:hover { color: var(--dsw-alias-label-primary); }',
  '.lc-gran-on, .lc-gran-on:hover { background: var(--dsw-alias-button-primary-fill); color: var(--dsw-alias-label-primary-foreground); }',
  '.lc-overview-num { margin-bottom: 8px; }',
  '.lc-overview-num b { font-size: 20px; }',
  '.lc-overview-num span { color: var(--dsw-alias-label-secondary); }',
  '.lc-stacked-wrap { position: relative; width: 100%; }',
  '.lc-stacked { display: flex; width: 100%; border-radius: 5px; overflow: hidden; background: rgba(128,128,128,0.18); position: relative; }',
  // Hover reference frame around the OCCUPIED region of the composition bar:
  // dashes from the left edge to the used/window boundary, so the legend's
  // "share of used" percentages visibly map to the boxed part (the free track
  // sits outside it). pointer-events: none keeps hover on the segments/free.
  '.lc-occupied-box { position: absolute; top: 0; bottom: 0; left: 0; border: 1px dashed var(--dsw-alias-brand-primary); border-radius: 5px; box-sizing: border-box; pointer-events: none; opacity: 0.9; }',
  '.lc-bar-tip { position: absolute; bottom: calc(100% + 6px); transform: translateX(-50%); z-index: 5; white-space: nowrap; background: var(--dsw-alias-bg-layer-2); border: 1px solid var(--dsw-alias-border-l1); border-radius: 6px; padding: 3px 8px; font-size: 12px; color: var(--dsw-alias-label-primary); box-shadow: 0 2px 8px rgba(0,0,0,0.18); pointer-events: none; }',
  '.lc-stacked > div { height: 100%; }',
  '.lc-stacked-seg-on { filter: brightness(1.18); }',
  '.lc-stacked-free-on { box-shadow: inset 0 0 0 1px var(--dsw-alias-label-secondary); border-radius: 3px; }',
  '.lc-legend { display: flex; flex-wrap: wrap; gap: 6px 14px; margin-top: 10px; }',
  '.lc-chip { display: inline-flex; align-items: center; gap: 5px; color: var(--dsw-alias-label-primary); }',
  '.lc-chip i, .lc-detail-row i, .lc-node i { display: inline-block; width: 8px; height: 8px; border-radius: 2px; }',
  '.lc-chip em { font-style: normal; color: var(--dsw-alias-label-secondary); }',
  '.lc-chip-on { font-weight: 600; }',
  '.lc-chip-on i { box-shadow: 0 0 0 1px var(--dsw-alias-brand-primary); }',
  '.lc-tools { margin-top: 10px; color: var(--dsw-alias-label-secondary); display: flex; flex-wrap: wrap; gap: 6px; align-items: center; }',
  '.lc-tool-chip { background: var(--dsw-alias-bg-layer-2); border-radius: 4px; padding: 1px 7px; font-size: 12px; color: var(--dsw-alias-label-primary); }',
  '.lc-chartrow { display: flex; gap: 6px; align-items: stretch; }',
  '.lc-axis { position: relative; width: 40px; height: 150px; padding-top: 18px; box-sizing: border-box; color: var(--dsw-alias-label-secondary); font-size: 11px; }',
  '.lc-axis span { position: absolute; right: 0; line-height: 1; }',
  '.lc-axis-top { top: 13px; }',
  '.lc-axis-mid { top: 69px; }',
  '.lc-axis-bot { top: 125px; }',
  '.lc-chart-scroll { position: relative; flex: 1; overflow-x: auto; overflow-y: hidden; min-width: 0; scrollbar-width: thin; }',
  '.lc-chart-scroll::-webkit-scrollbar { height: 8px; }',
  '.lc-chart-scroll::-webkit-scrollbar-thumb { background: color-mix(in srgb, var(--dsw-alias-label-secondary) 45%, transparent); border-radius: 4px; }',
  '.lc-chart-scroll::-webkit-scrollbar-thumb:hover { background: color-mix(in srgb, var(--dsw-alias-label-secondary) 70%, transparent); }',
  '.lc-chart-scroll::-webkit-scrollbar-track { background: transparent; }',
  '.lc-chart-fade { position: absolute; top: 0; bottom: 0; width: 26px; pointer-events: none; z-index: 2; }',
  '.lc-chart-fade-l { left: 0; background: linear-gradient(to right, var(--dsw-alias-bg-layer-1), transparent); }',
  '.lc-chart-fade-r { right: 0; background: linear-gradient(to left, var(--dsw-alias-bg-layer-1), transparent); }',
  '.lc-chart { position: relative; display: flex; align-items: flex-end; gap: 2px; height: 130px; padding-top: 18px; box-sizing: border-box; width: max-content; min-width: 100%; }',
  '.lc-grid { position: absolute; left: 0; right: 0; border-top: 1px dashed var(--dsw-alias-border-l1); pointer-events: none; }',
  '.lc-grid-top { top: 18px; }',
  '.lc-grid-mid { top: 74px; }',
  '.lc-bar { position: relative; width: 14px; flex: none; height: 100%; display: flex; align-items: flex-end; cursor: pointer; border-radius: 2px; transition: opacity 120ms ease; }',
  // Turn-aware dimming: while a turn is focused, bars OUTSIDE the active
  // turn fade to 35% and the whole current turn stays fully opaque.
  '.lc-chart-dim .lc-bar { opacity: 0.35; }',
  '.lc-chart-dim .lc-bar-in-turn { opacity: 1; }',
  '.lc-chart-dim .lc-turn { opacity: 0.35; }',
  '.lc-chart-dim .lc-turn-on { opacity: 1; }',
  '.lc-chart-tip { position: absolute; top: 0; transform: translateX(-50%); z-index: 5; white-space: nowrap; background: var(--dsw-alias-bg-layer-2); border: 1px solid var(--dsw-alias-border-l1); border-radius: 6px; padding: 3px 8px; font-size: 12px; color: var(--dsw-alias-label-primary); box-shadow: 0 2px 8px rgba(0,0,0,0.18); pointer-events: none; }',
  '.lc-bar:hover { background: var(--dsw-alias-bg-layer-2); }',
  '.lc-bar-selected { outline: 2px solid var(--dsw-alias-brand-primary); outline-offset: 1px; }',
  '.lc-bar-hovered { outline: 1px dashed var(--dsw-alias-brand-primary); outline-offset: 1px; }',
  '.lc-bar-in-turn { background: rgba(99,102,241,0.14); }',
  '.lc-bar-stack { display: flex; flex-direction: column-reverse; width: 100%; }',
  '.lc-bar-stack > div { width: 100%; }',
  '.lc-bar-marker { position: absolute; top: -16px; left: 50%; transform: translateX(-50%); font-size: 11px; color: var(--dsw-alias-state-warn-primary); }',
  '.lc-turns { display: flex; gap: 2px; width: max-content; min-width: 100%; margin-top: 4px; }',
  '.lc-turn { flex: none; box-sizing: border-box; text-align: center; font-size: 10px; line-height: 14px; font-weight: 600; color: #fff; border-radius: 3px; height: 14px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; cursor: default; transition: filter 120ms, opacity 120ms; }',
  '.lc-turn-on { filter: brightness(1.35); box-shadow: 0 0 0 1px rgba(255,255,255,0.4); }',
  '.lc-detail { margin-top: 12px; border-top: 1px solid var(--dsw-alias-border-l1); padding-top: 12px; }',
  '.lc-detail-head { display: flex; flex-wrap: wrap; gap: 6px 16px; margin-bottom: 8px; color: var(--dsw-alias-label-secondary); }',
  '.lc-detail-head b { color: var(--dsw-alias-label-primary); }',
  '.lc-detail-marker { color: var(--dsw-alias-state-warn-primary); font-size: 11px; background: var(--dsw-alias-bg-layer-2); border-radius: 6px; padding: 1px 7px; }',
  '.lc-detail-head .lc-actual { color: var(--dsw-alias-state-success-primary); }',
  '.lc-detail-tag { background: var(--dsw-alias-bg-layer-2); border: 1px solid var(--dsw-alias-border-l1); border-radius: 4px; padding: 0 6px; font-size: 11px; color: var(--dsw-alias-label-secondary); }',
  '.lc-detail-rows { margin-top: 10px; display: grid; grid-template-columns: 1fr 1fr; gap: 4px 24px; }',
  '.lc-detail-row { display: flex; align-items: center; gap: 8px; }',
  '.lc-detail-label { min-width: 70px; white-space: nowrap; color: var(--dsw-alias-label-secondary); }',
  '.lc-bar-track { flex: 1; height: 5px; border-radius: 3px; background: rgba(128,128,128,0.18); overflow: hidden; display: block; }',
  '.lc-bar-fill { display: block; height: 100%; border-radius: 3px; }',
  '.lc-detail-num { width: 44px; text-align: right; }',
  '.lc-detail-pct { width: 34px; text-align: right; color: var(--dsw-alias-label-secondary); }',
  '.lc-cols { display: flex; gap: 14px; flex-wrap: wrap; }',
  '.lc-col { flex: 1; min-width: 280px; }',
  '.lc-events, .lc-nodes { display: flex; flex-direction: column; gap: 2px; max-height: 320px; overflow-y: auto; }',
  '.lc-event { display: flex; align-items: center; gap: 8px; padding: 3px 0; }',
  '.lc-event-icon { width: 18px; text-align: center; color: var(--dsw-alias-state-warn-primary); }',
  '.lc-event-icon.lc-event-inject { color: #a855f7; }',
  '.lc-event-icon.lc-event-model { color: var(--dsw-alias-brand-primary); }',
  '.lc-event-label { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }',
  '.lc-event-at { flex: none; color: var(--dsw-alias-label-secondary); font-size: 11px; white-space: nowrap; }',
  '.lc-event-tokens { color: var(--dsw-alias-state-success-primary); }',
  '.lc-event-tokens.lc-up { color: var(--dsw-alias-state-warn-primary); }',
  '.lc-event-time { color: var(--dsw-alias-label-secondary); font-size: 12px; }',
  '.lc-node { display: flex; align-items: center; gap: 8px; padding: 3px 0; }',
  '.lc-node-preview { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: var(--dsw-alias-label-primary); }',
  '.lc-node-time { color: var(--dsw-alias-label-secondary); font-size: 12px; min-width: 54px; text-align: right; }',
  '.lc-node-tokens { color: var(--dsw-alias-label-secondary); }',
  '.lc-nodes-more { color: var(--dsw-alias-label-secondary); padding: 3px 0; }',
  '.lc-empty { color: var(--dsw-alias-label-secondary); padding: 18px 0; text-align: center; }',
  '.lc-foot { color: var(--dsw-alias-label-secondary); font-size: 12px; margin-top: 4px; }',
].join('\n')
